### ISSUE TITLE
Cannot use 'in' operator to search for 'country_code' in null

### ISSUE THREAD

**Issue by AlbertoFdzM** [Dabolus/cookie-consent#3]
Hi! Nice component!

I'm using the v1 if this component and I was trying to not check the user country, I just want to always show the cookie banner not matter where they are (At this moment there's no way to disable this in the component) so what I did was to set the `geoIpUrl` to nothing (`geo-ip-url=""`) and after this the console output this:

```
cookie-consent.html:274 Uncaught TypeError: Cannot use 'in' operator to search for 'country_code' in null
    at HTMLElement._checkCountryCode (cookie-consent.html:274)
    at HTMLElement.handler (polymer.html:507)
    at HTMLElement.fire (polymer.html:1284)
    at HTMLElement._handleResponse (iron-ajax.html:512)
    at <anonymous>
```

I checked the component's code and there's a line where you check if there's a property with the name set in `geoIpParam` inside the `response` of the `iron-request`.
https://github.com/Dabolus/cookie-consent/blob/master/cookie-consent.html#L280

_**Note:** This is happenning on the v2 too._

The problem is that before this `if` you check if `response` is an `object`:
https://github.com/Dabolus/cookie-consent/blob/2.0/cookie-consent.html#L277

And in my use case `response` is `null` and `typeof null === 'object'` is `true`.

I've created 2 PR to fix this in both versions (v1 and v2)

https://github.com/Dabolus/cookie-consent/pull/1
https://github.com/Dabolus/cookie-consent/pull/2

Thanks for your time and regards.

**Comment by Dabolus** [comment]
Hi!

I'm really sorry, I didn't check this repository for a lot of time.
Thank you for noticing this bug! If you open the PRs again, I would be glad to merge them.

Dabolus

**Comment by AlbertoFdzM** [comment]
There you go! Opened again, thanks for letting me collaborate. 😄 

#6
#7

**Comment by Dabolus** [comment]
Thank you so much! Closing the issue.

Dabolus
